### ISSUE TITLE
Add the topic datenstrom-yellow

### ISSUE THREAD

**Issue by markseuffert** [GiovanniSalmeri/yellow-disqus#2]
Hello Giovanni! 

Here's a tip from the Datenstrom Yellow maintainers. Please add the topic `datenstrom-yellow` to your repository. https://github.com/topics/datenstrom-yellow

Thanks again for developing/maintaining extensions, this is much appreciated. 👍

**Comment by GiovanniSalmeri** [comment]
Done! Thank you very much for the tip.
