### ISSUE TITLE
Previously maintained by Datenstrom

### ISSUE THREAD

**Issue by markseuffert** [GiovanniSalmeri/yellow-disqus#7]
Hello Giovanni, I have seen Disqus extension and Instagram extension mention that they were "previously maintained by Datenstrom". One wonders who that could be. After looking at the old file history, I saw that I was the only code contributor until 2021. If you like you can add my name or remove Datenstrom completely from these README. From my side acknowledgements are not needed. I am already listed as a contributor and happy that you were interesting to take over as the new maintainer. 

Thanks again for developing and taking such good care of extensions. 😀

**Comment by GiovanniSalmeri** [comment]
I have added your name, thank you! I love to name names 😊
